export const phrases: string[] = [
  "fetching votes",
  "untangling cables",
  "oiling gears",
  "inflating balloons",
  "brewing coffee",
  "calibrating senses",
  "counting sheep",
  "aligning stars",
  "debugging laughter",
  "practicing patience",
  "microwaving popcorn",
  "juggling ideas",
  "polishing crystals",
  "summoning voters",
  "taming butterflies",
  "wrangling llamas",
  "conjuring magic",
  "testing patience",
  "chasing unicorns",
  "brainstorming solutions",
  "tickling funny bones",
  "hatching plans",
  "mastering the art of waiting",
  "practicing zen meditation",
  "rehearsing victory speeches",
  "contemplating life's mysteries",
  "taming wild thoughts",
  "brewing new ideas",
  "summoning the muse",
  "dancing the waiting tango",
  "wrapping presents",
  "twiddling thumbs",
  "warming up vocal cords",
  "playing air guitar",
  "polishing crystal balls",
  "summoning courage",
  "building castles in the air",
  "counting down the seconds",
  "searching for the missing piece",
  "trying to catch a rainbow",
  "hitting the griddy",
];
